spring: 
  datasource: 
     url: jdbc:mysql://localhost:3306/muzixdb
     username: root
     password: Root@123
  jpa: 
    hibernate: 
      ddl-auto: update
    show-sql: true
    
server:
  port: 8089
